# Cleaning Data
let's load the dataset to understand it.

In [2]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\scleber\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\scleber\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Vizualization

In [3]:
import pandas as pd

# Load the csv file 

df=pd.read_csv('../DATA/raw/dirty_cafe_sales.csv')

# Display the first few rows of the dataframe

print(df.head())

  Transaction ID    Item Quantity Price Per Unit Total Spent  Payment Method  \
0    TXN_1961373  Coffee        2            2.0         4.0     Credit Card
1    TXN_4977031    Cake        4            3.0        12.0            Cash
2    TXN_4271903  Cookie        4            1.0       ERROR     Credit Card
3    TXN_7034554   Salad        2            5.0        10.0         UNKNOWN
4    TXN_3160411  Coffee        2            2.0         4.0  Digital Wallet

   Location Transaction Date
0  Takeaway       2023-09-08
1  In-store       2023-05-16
2  In-store       2023-07-19
3   UNKNOWN       2023-04-27
4  In-store       2023-06-11

As we can see there is some problemns in the data, like 'ERROR' or 'UNKOWN' that we should trade for NaN.

## Columns type

In [4]:

print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB
None

The columns 'Item', 'Quantity', 'Price Per Unit' and 'Total Spent' shold be numeric. Also 'Transaction Date' shold be DataTime.

### Impossible Datas
We gonna see each colum to look for impossible datas.

In [11]:
print(f"{'Item'}: {df['Item'].unique()} unique values")

Item: <StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str unique values

In [12]:
print(f"{'Quantity'}: {df['Quantity'].unique()} unique values")

Quantity: <StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str unique values

In [13]:
print(f"{'Price Per Unit'}: {df['Price Per Unit'].unique()} unique values")

Price Per Unit: <StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str unique values

In [14]:
print(f"{'Total Spent'}: {df['Total Spent'].unique()} unique values")

Total Spent: <StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str unique values

In [15]:
print(f"{'Payment Method'}: {df['Payment Method'].unique()} unique values")

Payment Method: <StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str unique values

In [16]:
print(f"{'Location'}: {df['Location'].unique()} unique values")

Location: <StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str unique values

In [18]:
# verificating the ID 
invalid_ids = df[
    ~df["Transaction ID"].str.match(r"^TXN_\d+$", na=False)
]
invalid_ids

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [21]:
# verificanting the Transaction Date
# We will check for non-null values that do not match the expected date format (YYYY-MM-DD) and also exclude known invalid entries like "ERROR", "UNKNOWN", and "UNKOWN".
mask = (
    df["Transaction Date"].notna()
    &
    ~df["Transaction Date"].isin(
        ["ERROR", "UNKNOWN", "UNKOWN"]
    )
)

invalid_dates = df[
    mask &
    ~df["Transaction Date"].str.match(
        r"^\d{4}-\d{2}-\d{2}$",
        na=False
    )
]

invalid_dates

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

As we can see, there's no impossible Datas to fix.

In [1]:
import json

with open("01-data_understanding.ipynb", "r", encoding="utf-8") as f:
    json.load(f)

print("OK")

JSONDecodeError: Expecting value: line 1 column 1 (char 0)